### ISSUE TITLE
Consider using widget instead

### ISSUE THREAD

**Issue by DyKarN** [Cristishor201/RailNationBot#16]
Widget seems like a faster and easier way of doing it

**Comment by Cristishor201** [comment]
now I saw this issue. :+1: 
I am already working on this....

**Comment by Cristishor201** [comment]
@DyKarN  I updated the project with a version of the widget that works at the momement, but however it's very hard to stop the script. you have only 2 seconds window to close it. This is one reason that I don't want to release the version just yet, and also because it's incomplet : if you have your widget elsewhere the default position, it won't works.

I let you know if you want to use this work, in game, until I came up with something more stable as a official release.

**Comment by Cristishor201** [comment]
for using, download / clone this repository as ZIP
